name: "Build and Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  unit-tests:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout the code
        uses: actions/checkout@v2.6.0
      
      - name: Setup JAVA 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      
      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      
      - name: Run lint
        run: ./gradlew lintDebug
      
      - name: Run Unit Test
        run: ./gradlew test
      
      - name: Show Unit Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
        
