name: "Build and Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  unit-tests:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout the code
        uses: actions/checkout@v3
      
      - name: Setup JAVA 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      
      - name: Cache gradle and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      
      - name: Run lint
        run: ./gradlew lintDebug
        
      - name: Upload lint test report
        uses: actions/upload-artifact@v3
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html
      
      - name: Run unit test
        run: ./gradlew :app:testDebugUnitTest --tests "me.bincy.movielist.ui.viewmodel.MovieListViewModelTest"
      
      - name: Upload unit test report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test results
          path: ./**/build/reports/tests/**/me.bincy.movielist.ui.viewmodel.MovieListViewModelTest.html
          retention-days: 1
          
      - name: Show unit test report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} 
        
